import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "fr" | "en" | "ar";

const dictionaries = {
  fr: {
    navHome: "Accueil",
    navServices: "Services",
    navAbout: "A Propos",
    navContact: "Contact",
    freeQuote: "Devis Gratuit",
    heroBadge: "Fourniture - Pose - Maintenance",
    heroTitle: "Solutions de securite completes pour votre entreprise",
    heroText: "GSV accompagne entreprises, administrations et particuliers avec des systemes de securite fiables et durables.",
    quoteButton: "Demander un devis gratuit",
    servicesButton: "Voir nos services",
    aboutUs: "A propos de nous",
    readMore: "Lire plus",
    servicesEyebrow: "Nos Services",
    servicesTitle: "10 domaines d'expertise securite & IT",
    contact: "Contact",
    footerText: "Votre partenaire de confiance pour des solutions de securite completes. Expertise, fiabilite et protection 24/7.",
    rights: "Tous droits reserves.",
    certified: "Certifie & Agree",
    partnersEyebrow: "Partenaires",
    partnersTitle: "Ils nous font confiance",
    partnersText: "Nous sommes fiers de collaborer avec des leaders de l'industrie grace a nos solutions de securite integrees.",
    locationEyebrow: "Localisation",
    locationTitle: "Retrouvez GLOBAL SECURITY VISION",
    locationText: "Visitez-nous ou lancez directement l'itineraire depuis Google Maps pour rejoindre notre equipe.",
    openRoute: "Ouvrir l'itineraire",
    realisationsEyebrow: "Nos realisations",
    realisationsTitle: "Des installations realisees sur le terrain",
    realisationsText: "Quelques exemples de nos travaux en videosurveillance, reseaux, controle et equipements de securite.",
    previousRealisation: "Realisation precedente",
    nextRealisation: "Realisation suivante",
    realisation: "Realisation",
    video: "Video",
    photo: "Photo",
    outOf: "sur",
    faqEyebrow: "FAQ",
    faqTitle: "Questions ?",
    faqText: "Obtenez des reponses claires sur nos installations de securite et notre support technique.",
    whyEyebrow: "Pourquoi GSV",
    whyTitle: "Une expertise reconnue depuis 15 ans",
    whyText: "Fondee en 2009, GSV s'est imposee comme reference nationale en solutions de securite integrees. Plus de 1 200 projets realises a travers le pays.",
    testimonialsEyebrow: "Temoignages",
    testimonialsTitle: "Ce que disent nos clients",
    finalCtaTitle: "Pret a securiser votre site ?",
    finalCtaText: "Contactez-nous pour une etude gratuite et un devis personnalise adapte a vos besoins.",
    contactUs: "Nous contacter",
    aboutPreviewText: "Fondee en 2020, GLOBAL SECURITY VISION est specialisee dans les solutions de securite integrees. Nous realisons un diagnostic pousse afin de proposer des services adaptes a chaque client.",
    homeServicesText: "De la videosurveillance au materiel bureautique, nous couvrons l'ensemble des besoins en securite electronique et infrastructure informatique.",
    learnMore: "En savoir plus",
    aboutHeroTitle: "GLOBAL SECURITY VISION",
    aboutHeroText: "Solutions de securite integrees, diagnostic pousse et accompagnement adapte a chaque client.",
    missionEyebrow: "Notre mission",
    missionTitle: "Proteger vos espaces avec des solutions fiables et efficaces",
    aboutFullText: "GLOBAL SECURITY VISION, fondee en 2020, est une entreprise specialisee dans les solutions de securite integrees. Nous offrons des services de videosurveillance, systemes anti-intrusion, alarmes incendie, automatisation, controle d'acces, et bien plus encore. Nous realisons un diagnostic pousse afin de determiner vos besoins et proposons des services parfaitement adaptes a chaque client pour ameliorer la securite de votre site. Grace a notre expertise et a notre approche innovante, nous protegeons vos espaces avec des solutions fiables et efficaces.",
    expertiseEyebrow: "Expertise",
    expertiseTitle: "Ce que nous faisons",
    contactHeroEyebrow: "Contact & Devis",
    contactHeroTitle: "Parlons de votre projet",
    contactHeroText: "Notre equipe vous repond sous 24h avec une proposition adaptee a vos besoins et votre budget.",
    formTitle: "Demande de devis gratuit",
    requiredText: "Les champs marques * sont obligatoires.",
    nameLabel: "Nom complet",
    customerTypeLabel: "Type de client",
    companyLabel: "Societe / Organisme",
    emailLabel: "Email",
    phoneLabel: "Telephone",
    serviceLabel: "Service concerne",
    messageLabel: "Description du besoin",
    companyType: "Entreprise",
    individualType: "Particulier",
    selectService: "Selectionner un service...",
    messagePlaceholder: "Decrivez votre projet...",
    sendRequest: "Envoyer la demande",
    sending: "Envoi en cours...",
    sentTitle: "Message envoye !",
    sentText: "Merci pour votre demande. Notre equipe vous contactera dans les meilleurs delais.",
    newRequest: "Nouvelle demande",
    requiredError: "Veuillez remplir tous les champs obligatoires.",
    address: "Adresse",
    hours: "Horaires",
    servicesHeroTitle: "Des solutions de securite completes, installees proprement",
    servicesHeroText: "GSV accompagne les entreprises, commerces, institutions et particuliers avec des systemes fiables, evolutifs et faciles a utiliser au quotidien.",
    requestQuote: "Demander un devis",
    expertiseServicesTitle: "Chaque besoin a sa solution",
    expertiseServicesText: "Choisissez un service, expliquez-nous votre site, puis notre equipe vous propose une solution adaptee a votre budget et vos contraintes.",
    requestThisService: "Demander ce service",
    methodEyebrow: "Methode",
    methodTitle: "Un projet propre du diagnostic a la maintenance",
    methodText: "Notre equipe analyse votre site, recommande le bon materiel, realise une installation nette, puis reste disponible pour les reglages, extensions et maintenances.",
    freeQuoteEyebrow: "Devis gratuit",
    siteSecureTitle: "Vous avez un site a securiser ?",
    siteSecureText: "Envoyez-nous votre besoin, meme approximatif. Nous vous aidons a choisir le bon systeme sans surdimensionner votre installation.",
  },
  en: {
    navHome: "Home",
    navServices: "Services",
    navAbout: "About",
    navContact: "Contact",
    freeQuote: "Free Quote",
    heroBadge: "Supply - Installation - Maintenance",
    heroTitle: "Complete security solutions for your business",
    heroText: "GSV supports companies, institutions and individuals with reliable, long-lasting security systems.",
    quoteButton: "Request a free quote",
    servicesButton: "View services",
    aboutUs: "About us",
    readMore: "Read more",
    servicesEyebrow: "Our Services",
    servicesTitle: "10 security & IT areas of expertise",
    contact: "Contact",
    footerText: "Your trusted partner for complete security solutions. Expertise, reliability and 24/7 protection.",
    rights: "All rights reserved.",
    certified: "Certified & Approved",
    partnersEyebrow: "Partners",
    partnersTitle: "Trusted by our clients",
    partnersText: "We are proud to work with leading organizations through our integrated security solutions.",
    locationEyebrow: "Location",
    locationTitle: "Find GLOBAL SECURITY VISION",
    locationText: "Visit us or open Google Maps directions to reach our team.",
    openRoute: "Open directions",
    realisationsEyebrow: "Our work",
    realisationsTitle: "Field installations completed by GSV",
    realisationsText: "Examples of our work in CCTV, networks, access control and security equipment.",
    previousRealisation: "Previous work",
    nextRealisation: "Next work",
    realisation: "Project",
    video: "Video",
    photo: "Photo",
    outOf: "of",
    faqEyebrow: "FAQ",
    faqTitle: "Questions?",
    faqText: "Get clear answers about our security installations and technical support.",
    whyEyebrow: "Why GSV",
    whyTitle: "Recognized expertise for over 15 years",
    whyText: "Founded in 2009, GSV has become a national reference for integrated security solutions with more than 1,200 completed projects.",
    testimonialsEyebrow: "Testimonials",
    testimonialsTitle: "What our clients say",
    finalCtaTitle: "Ready to secure your site?",
    finalCtaText: "Contact us for a free assessment and a quote tailored to your needs.",
    contactUs: "Contact us",
    aboutPreviewText: "Founded in 2020, GLOBAL SECURITY VISION specializes in integrated security solutions. We run a detailed diagnosis to offer services adapted to every client.",
    homeServicesText: "From CCTV to office IT equipment, we cover all electronic security and IT infrastructure needs.",
    learnMore: "Learn more",
    aboutHeroTitle: "GLOBAL SECURITY VISION",
    aboutHeroText: "Integrated security solutions, detailed diagnosis and support adapted to every client.",
    missionEyebrow: "Our mission",
    missionTitle: "Protecting your spaces with reliable and efficient solutions",
    aboutFullText: "GLOBAL SECURITY VISION, founded in 2020, is a company specialized in integrated security solutions. We provide CCTV, intrusion systems, fire alarms, automation, access control and much more. We perform a thorough diagnosis to identify your needs and offer services perfectly adapted to each client to improve site security. With our expertise and innovative approach, we protect your spaces with reliable and effective solutions.",
    expertiseEyebrow: "Expertise",
    expertiseTitle: "What we do",
    contactHeroEyebrow: "Contact & Quote",
    contactHeroTitle: "Tell us about your project",
    contactHeroText: "Our team replies within 24 hours with a proposal adapted to your needs and budget.",
    formTitle: "Free quote request",
    requiredText: "Fields marked * are required.",
    nameLabel: "Full name",
    customerTypeLabel: "Customer type",
    companyLabel: "Company / Organization",
    emailLabel: "Email",
    phoneLabel: "Phone",
    serviceLabel: "Service",
    messageLabel: "Project description",
    companyType: "Company",
    individualType: "Individual",
    selectService: "Select a service...",
    messagePlaceholder: "Describe your project...",
    sendRequest: "Send request",
    sending: "Sending...",
    sentTitle: "Message sent!",
    sentText: "Thank you for your request. Our team will contact you as soon as possible.",
    newRequest: "New request",
    requiredError: "Please fill in all required fields.",
    address: "Address",
    hours: "Opening hours",
    servicesHeroTitle: "Complete security solutions, cleanly installed",
    servicesHeroText: "GSV supports companies, shops, institutions and individuals with reliable, scalable systems that are easy to use daily.",
    requestQuote: "Request a quote",
    expertiseServicesTitle: "Every need has a solution",
    expertiseServicesText: "Choose a service, tell us about your site, and our team will recommend a solution adapted to your budget and constraints.",
    requestThisService: "Request this service",
    methodEyebrow: "Method",
    methodTitle: "A clean project from diagnosis to maintenance",
    methodText: "Our team analyzes your site, recommends the right equipment, performs a clean installation, then remains available for adjustments, extensions and maintenance.",
    freeQuoteEyebrow: "Free quote",
    siteSecureTitle: "Do you have a site to secure?",
    siteSecureText: "Send us your need, even roughly. We help you choose the right system without oversizing your installation.",
  },
  ar: {
    navHome: "الرئيسية",
    navServices: "الخدمات",
    navAbout: "من نحن",
    navContact: "اتصل بنا",
    freeQuote: "طلب عرض سعر",
    heroBadge: "توريد - تركيب - صيانة",
    heroTitle: "حلول أمنية متكاملة لحماية مؤسستك",
    heroText: "ترافقكم GSV بحلول أمنية موثوقة ومستدامة للشركات والمؤسسات والأفراد.",
    quoteButton: "اطلب عرض سعر مجاني",
    servicesButton: "عرض الخدمات",
    aboutUs: "من نحن",
    readMore: "اقرأ المزيد",
    servicesEyebrow: "خدماتنا",
    servicesTitle: "10 مجالات خبرة في الأمن وتقنية المعلومات",
    contact: "اتصل بنا",
    footerText: "شريككم الموثوق لحلول أمنية متكاملة، بخبرة عالية وحماية متواصلة على مدار الساعة.",
    rights: "جميع الحقوق محفوظة.",
    certified: "معتمد ومرخص",
    partnersEyebrow: "الشركاء",
    partnersTitle: "يثقون بنا",
    partnersText: "نفخر بالتعاون مع مؤسسات رائدة بفضل حلولنا الأمنية المتكاملة.",
    locationEyebrow: "الموقع",
    locationTitle: "موقع GLOBAL SECURITY VISION",
    locationText: "زورونا أو افتحوا الاتجاهات مباشرة عبر خرائط Google للوصول إلى فريقنا.",
    openRoute: "فتح الاتجاهات",
    realisationsEyebrow: "أعمالنا",
    realisationsTitle: "تركيبات ميدانية أنجزتها GSV",
    realisationsText: "نماذج من أعمالنا في كاميرات المراقبة والشبكات والتحكم في الدخول وتجهيزات الأمن.",
    previousRealisation: "العمل السابق",
    nextRealisation: "العمل التالي",
    realisation: "إنجاز",
    video: "فيديو",
    photo: "صورة",
    outOf: "من",
    faqEyebrow: "الأسئلة الشائعة",
    faqTitle: "هل لديك أسئلة؟",
    faqText: "احصل على إجابات واضحة حول تركيباتنا الأمنية والدعم التقني.",
    whyEyebrow: "لماذا GSV",
    whyTitle: "خبرة موثوقة منذ أكثر من 15 سنة",
    whyText: "أصبحت GSV مرجعاً وطنياً في حلول الأمن المتكاملة مع أكثر من 1200 مشروع منجز.",
    testimonialsEyebrow: "آراء العملاء",
    testimonialsTitle: "ماذا يقول عملاؤنا",
    finalCtaTitle: "هل أنت جاهز لتأمين موقعك؟",
    finalCtaText: "تواصل معنا للحصول على دراسة مجانية وعرض سعر مخصص حسب احتياجاتك.",
    contactUs: "اتصل بنا",
    aboutPreviewText: "تأسست GLOBAL SECURITY VISION سنة 2020 وهي متخصصة في حلول الأمن المتكاملة. نقوم بتشخيص دقيق لنقترح خدمات مناسبة لكل عميل.",
    homeServicesText: "من كاميرات المراقبة إلى تجهيزات الإعلام الآلي والمكاتب، نغطي احتياجات الأمن الإلكتروني والبنية التحتية المعلوماتية.",
    learnMore: "اعرف المزيد",
    aboutHeroTitle: "GLOBAL SECURITY VISION",
    aboutHeroText: "حلول أمنية متكاملة، تشخيص دقيق ومرافقة مناسبة لكل عميل.",
    missionEyebrow: "مهمتنا",
    missionTitle: "حماية مساحاتكم بحلول موثوقة وفعالة",
    aboutFullText: "تأسست GLOBAL SECURITY VISION سنة 2020 وهي شركة متخصصة في حلول الأمن المتكاملة. نقدم خدمات كاميرات المراقبة وأنظمة مكافحة التسلل وإنذارات الحريق والأتمتة والتحكم في الدخول وغيرها. نقوم بتشخيص دقيق لتحديد احتياجاتكم ونقترح خدمات مناسبة لكل عميل لتحسين أمن الموقع. بفضل خبرتنا ونهجنا المبتكر نحمي مساحاتكم بحلول موثوقة وفعالة.",
    expertiseEyebrow: "الخبرة",
    expertiseTitle: "ما نقدمه",
    contactHeroEyebrow: "اتصال وطلب عرض",
    contactHeroTitle: "حدثنا عن مشروعك",
    contactHeroText: "يرد فريقنا خلال 24 ساعة باقتراح مناسب لاحتياجاتك وميزانيتك.",
    formTitle: "طلب عرض سعر مجاني",
    requiredText: "الحقول التي تحمل * إجبارية.",
    nameLabel: "الاسم الكامل",
    customerTypeLabel: "نوع العميل",
    companyLabel: "الشركة / المؤسسة",
    emailLabel: "البريد الإلكتروني",
    phoneLabel: "الهاتف",
    serviceLabel: "الخدمة المطلوبة",
    messageLabel: "وصف الاحتياج",
    companyType: "شركة",
    individualType: "فرد",
    selectService: "اختر خدمة...",
    messagePlaceholder: "صف مشروعك...",
    sendRequest: "إرسال الطلب",
    sending: "جار الإرسال...",
    sentTitle: "تم إرسال الرسالة!",
    sentText: "شكراً لطلبك. سيتواصل معك فريقنا في أقرب وقت.",
    newRequest: "طلب جديد",
    requiredError: "يرجى ملء جميع الحقول الإجبارية.",
    address: "العنوان",
    hours: "أوقات العمل",
    servicesHeroTitle: "حلول أمنية متكاملة بتركيب احترافي",
    servicesHeroText: "ترافق GSV الشركات والمتاجر والمؤسسات والأفراد بأنظمة موثوقة وقابلة للتطوير وسهلة الاستخدام يومياً.",
    requestQuote: "طلب عرض سعر",
    expertiseServicesTitle: "لكل احتياج حل مناسب",
    expertiseServicesText: "اختر الخدمة واشرح لنا موقعك، وسيقترح فريقنا حلاً يناسب ميزانيتك وقيودك.",
    requestThisService: "طلب هذه الخدمة",
    methodEyebrow: "المنهجية",
    methodTitle: "مشروع منظم من التشخيص إلى الصيانة",
    methodText: "يحلل فريقنا موقعك، يوصي بالمعدات المناسبة، ينجز تركيباً نظيفاً، ثم يبقى متاحاً للتعديلات والتوسعات والصيانة.",
    freeQuoteEyebrow: "عرض سعر مجاني",
    siteSecureTitle: "هل لديك موقع يحتاج إلى حماية؟",
    siteSecureText: "أرسل لنا احتياجك حتى لو كان تقريبياً. نساعدك في اختيار النظام المناسب دون تضخيم التكاليف.",
  },
} as const;

type DictionaryKey = keyof typeof dictionaries.fr;

type LanguageContextValue = {
  dir: "ltr" | "rtl";
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: DictionaryKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("gsv-language");
    return saved === "en" || saved === "ar" || saved === "fr" ? saved : "fr";
  });
  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    localStorage.setItem("gsv-language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [dir, language]);

  const value = useMemo(
    () => ({
      dir,
      language,
      setLanguage,
      t: (key: DictionaryKey) => dictionaries[language][key],
    }),
    [dir, language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return value;
}

export const languageOptions = [
  { value: "fr", label: "Français" },
  { value: "en", label: "English" },
  { value: "ar", label: "العربية" },
] satisfies Array<{ value: Language; label: string }>;
